package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/pejas/kagen/internal/ui"
)

// defaultDevfileContent is the minimal devfile generated by `kagen init`.
const defaultDevfileContent = `schemaVersion: 2.2.0
metadata:
  name: kagen-workspace
  version: 1.0.0
components:
  - name: agent
    container:
      image: node:20-slim
      command: ["tail", "-f", "/dev/null"]
      env:
        - name: PROMPT_COMMAND
          value: "history -a; history -c; history -r"
      volumeMounts:
        - name: agent-auth
          path: /home/node/.claude
        - name: projects
          path: /projects
`

// defaultKagenConfig is the default project-level kagen config.
const defaultKagenConfig = `# kagen project configuration
# See https://github.com/pejas/kagen for documentation.

# Default agent for this project (claude, codex, opencode).
# agent: claude

# Additional egress destinations beyond agent API defaults.
# proxy_allowlist:
#   - registry.npmjs.org
#   - pypi.org
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Bootstrap local project configuration",
	Long: `Initialize a kagen project in the current repository.
Creates devfile.yaml if it does not already exist. 
Project-specific overrides can be added manually to .kagen.yaml if needed.
This command is idempotent — running it again is a safe no-op.`,
	RunE: runInit,
}

func runInit(_ *cobra.Command, _ []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	devfilePath := filepath.Join(cwd, "devfile.yaml")
	created := false

	devfileCreated, err := createIfMissing(devfilePath, defaultDevfileContent)
	if err != nil {
		return err
	}
	if devfileCreated {
		ui.Success("Created %s", devfilePath)
		created = true
	}

	if !created {
		ui.Info("Project already initialized — nothing to do")
	}

	return nil
}

// createIfMissing writes content to path only if the file does not exist.
// Returns true if the file was created, false if it already existed.
func createIfMissing(path, content string) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil // Already exists.
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("creating %s: %w", filepath.Base(path), err)
	}

	return true, nil
}
